HT_13/ht_13/ht_13/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from news import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('results/', include('news.urls')),
    re_path('^$', views.index, name='index'),

]

HT_13/ht_13/news/urls.py
from django.urls import path, re_path
from news import views


app_name = 'news'
urlpatterns = [
    re_path('^$', views.get_stories, name='get_stories'),
    path('<int:story_id>/', views.story_detail, name='story_detail'),
    path('get_data/', views.get_data, name='get_data'),

]

HT_13/ht_13/news/models.py
from django.db import models


class Category(models.Model):
    category_name = models.CharField(max_length=50, null=False)

    def __str__(self):
        return self.category_name

    class Meta:
        verbose_name_plural = 'Categories'


class Story(models.Model):
    author = models.CharField(max_length=100, default='')
    descendants = models.CharField(max_length=100, default='')
    story_id = models.CharField(max_length=100, default='')
    kids = models.TextField(default='')
    score = models.IntegerField(default=0)
    text = models.TextField(default='')
    time = models.CharField(max_length=100, default='')
    title = models.CharField(max_length=100, default='')
    type = models.CharField(max_length=100, default='')
    url = models.URLField()
    category_id = models.ForeignKey(Category, on_delete=models
                                    .CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Stories'

HT_13/ht_13/news/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Story
from news.request_data import execute


def get_stories(request):
    askstories_list = Story.objects.filter(category_id=1).order_by('title')[:5]
    newstories_list = Story.objects.filter(category_id=2).order_by('title')[:5]
    jobstories_list = Story.objects.filter(category_id=3).order_by('title')[:5]
    showstories_list = Story.objects.filter(category_id=4).order_by('title')[:5]

    return render(request, 'news/results.html', {'askstories_list': askstories_list, 'newstories_list': newstories_list,
                                                 'jobstories_list': jobstories_list, 'showstories_list': showstories_list})

def story_detail(request, story_id):
    story = get_object_or_404(Story, pk=story_id)
    return render(request, 'news/details.html', {'story': story})


def index(request):
    return render(request, 'news/index.html')


def get_data(request):
    execute()
    return redirect('/results')

HT_13/ht_13/news/templates/news/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Title{% endblock %}</title>
    {% block static %}
        <link href="https://s3.us-east-2.amazonaws.com/python-test123/ht_13.css" rel="stylesheet" type="text/css" />
        <link href="https://s3.us-east-2.amazonaws.com/python-test123/blocks_styles.css" rel="stylesheet" type="text/css" />
        <link href="https://s3.us-east-2.amazonaws.com/python-test123/bootstrap.min.css" rel="stylesheet" media="screen">
        <script src="https://s3.us-east-2.amazonaws.com/python-test123/bootstrap.min.js"></script>
    {% endblock %}
</head>
<body>
{% block header %}
    {% include "news/header.html" %}
{% endblock %}

{% block menu %}
    {% include "news/menu.html" %}
{% endblock %}

{% block content %}
    {% include "news/content.html" %}
{% endblock %}

</body>
</html>

HT_13/ht_13/news/templates/news/content.html
<div class="w3-main w3-light-grey" id="belowtopnav" style="margin-left: 220px; padding-top: 0px;">
  <div class="w3-row w3-white">
    <div class="w3-col l10 m12" id="main">
      <div id="mainLeaderboard" style="overflow:hidden;">
        <!-- MainLeaderboard-->
        <div id="div-gpt-ad-1422003450156-2" data-google-query-id="CJjI29nTjNkCFQ-CGQodwrgJOQ">
          <script type="text/javascript">googletag.cmd.push(function() { googletag.display('div-gpt-ad-1422003450156-2'); });</script>
        <div id="google_ads_iframe_/16833175/MainLeaderboard_0__container__" style="border: 0pt none; display: inline-block; width: 728px; height: 90px;"><iframe frameborder="0" src="https://tpc.googlesyndication.com/safeframe/1-0-15/html/container.html" id="google_ads_iframe_/16833175/MainLeaderboard_0" title="3rd party ad content" name="" scrolling="no" marginwidth="0" marginheight="0" width="728" height="90" data-is-safeframe="true" style="border: 0px; vertical-align: bottom;"></iframe></div></div>
      </div>
<h1>Welcome to Stories Website</h1>

<div class="w3-padding w3-light-grey">
    <p class="w3-large" style="margin-bottom:30px;">1. What does SQL stand for?</p>
    <form role="form" name="quizform" action="quiztest.asp?qtest=SQL" method="post">
    <input type="hidden" name="starttime" value="2/4/2018 11:13:50 AM">
    <input type="hidden" name="answers" value="0000000000000000000000000" size="25">
    <input type="hidden" name="qnumber" value="1" size="25">
    <div class="radio"><label><input type="radio" name="quiz" id="2" value="2"> Structured Question Language</label></div><div class="radio"><label><input type="radio" name="quiz" id="1" value="1"> Structured Query Language</label></div><div class="radio"><label><input type="radio" name="quiz" id="3" value="3"> Strong Question Language</label></div>
    <br>
    <input type="submit" class="w3-btn w3-orange w3-large w3-text-white" value=" Next ">
    </form>
</div>

HT_13/ht_13/news/templates/news/details.html
{% extends 'news/base.html' %}

{% block title %}Story details{% endblock %}

{% block content %}

<div class="w3-main w3-light-grey" id="belowtopnav" style="margin-left: 220px; padding-top: 0px;">
  <div class="w3-row w3-white">
    <div class="w3-col l10 m12" id="main">
      <div id="mainLeaderboard" style="overflow:hidden;">
        <div id="div-gpt-ad-1422003450156-2" data-google-query-id="CJjI29nTjNkCFQ-CGQodwrgJOQ">
          <script type="text/javascript">googletag.cmd.push(function() { googletag.display('div-gpt-ad-1422003450156-2'); });</script>
        <div id="google_ads_iframe_/16833175/MainLeaderboard_0__container__" style="border: 0pt none; display: inline-block; width: 728px; height: 90px;"><iframe frameborder="0" src="https://tpc.googlesyndication.com/safeframe/1-0-15/html/container.html" id="google_ads_iframe_/16833175/MainLeaderboard_0" title="3rd party ad content" name="" scrolling="no" marginwidth="0" marginheight="0" width="728" height="90" data-is-safeframe="true" style="border: 0px; vertical-align: bottom;"></iframe></div></div>
      </div>

    <h1 style="text-align: center">{{ story.title}}</h1>
    <div class="container">
   <table class="table table-bordered">
    <tbody>
    <tr>
        <th>Author</th>
        <td>{{ story.author }}</td>
    </tr>
    <tr>
        <th>Text</th>
        <td>{{ story.text }}</td>
    </tr>
    <tr>
        <th>Score</th>
        <td>{{ story.score }}</td>
    </tbody>
  </table>
</div>

{% endblock %}

HT_13/ht_13/news/templates/news/header.html
<div class="w3-container top">
  <a class="w3schools-logo" href="//www.w3schools.com">w3schools<span class="dotcom">.com</span></a>
  <div class="w3-right w3-hide-small w3-wide toptext" style="font-family:'Segoe UI',Arial,sans-serif">THE WORLD'S LARGEST WEB DEVELOPER SITE</div>
</div>


<div class="w3-card-2 topnav" id="topnav" style="position: relative;">
  <div style="overflow:auto;">
    <div class="w3-bar w3-left" style="width:100%;overflow:hidden;height:44px">
      <a href="javascript:void(0);" class="topnav-icons fa fa-menu w3-hide-large w3-left w3-bar-item w3-button" onclick="open_menu()" title="Menu"></a>
      <a href="/default.asp" class="topnav-icons fa fa-home w3-left w3-bar-item w3-button" title="Home"></a>
      <a class="w3-bar-item w3-button" href="/html/default.asp" title="HTML Tutorial">HTML</a>
      <a class="w3-bar-item w3-button" href="/css/default.asp" title="CSS Tutorial">CSS</a>
      <a class="w3-bar-item w3-button" href="/js/default.asp" title="JavaScript Tutorial">JAVASCRIPT</a>
      <a class="w3-bar-item w3-button" href="/sql/default.asp" title="SQL Tutorial">SQL</a>
      <a class="w3-bar-item w3-button" href="/php/default.asp" title="PHP Tutorial">PHP</a>
      <a class="w3-bar-item w3-button" href="/bootstrap/default.asp" title="Bootstrap Tutorial">BOOTSTRAP</a>
      <a class="w3-bar-item w3-button" href="/howto/default.asp" title="How To">HOW TO</a>
      <a class="w3-bar-item w3-button" href="/jquery/default.asp" title="jQuery Tutorial">JQUERY</a>
      <a class="w3-bar-item w3-button" href="/w3css/default.asp" title="W3.CSS Tutorial">W3.CSS</a>
      <a class="w3-bar-item w3-button" href="/angular/default.asp" title="Angular Tutorial">ANGULAR</a>
      <a class="w3-bar-item w3-button" href="/xml/default.asp" title="XML Tutorial">XML</a>
      <a class="w3-bar-item w3-button" id="topnavbtn_tutorials" href="javascript:void(0);" onclick="w3_open_nav(&quot;tutorials&quot;)" title="Tutorials">MORE <i class="fa fa-caret-down"></i><i class="fa fa-caret-up" style="display:none"></i></a>
      <a href="javascript:void(0);" class="topnav-icons fa w3-right w3-bar-item w3-button" onclick="open_search(this)" title="Search W3Schools"></a>
      <a href="javascript:void(0);" class="topnav-icons fa w3-right w3-bar-item w3-button" onclick="open_translate(this)" title="Translate W3Schools"></a>
      <a class="w3-bar-item w3-button w3-right" href="/forum/default.asp">FORUM</a>
      <a class="w3-bar-item w3-button w3-right" id="topnavbtn_examples" href="javascript:void(0);" onclick="w3_open_nav(&quot;examples&quot;)" title="Examples">EXAMPLES <i class="fa fa-caret-down"></i><i class="fa fa-caret-up" style="display:none"></i></a>
      <a class="w3-bar-item w3-button w3-right" id="topnavbtn_references" href="javascript:void(0);" onclick="w3_open_nav(&quot;references&quot;)" title="References">REFERENCES <i class="fa fa-caret-down"></i><i class="fa fa-caret-up" style="display:none"></i></a>
    </div>
    <div id="nav_tutorials" class="w3-bar-block w3-card-2" style="display:none;">
      <span onclick="w3_close_nav(&quot;tutorials&quot;)" class="w3-button w3-xlarge w3-right" style="position:absolute;right:0;font-weight:bold;">×</span>
      <div class="w3-row-padding" style="padding:24px 48px">
        <div class="w3-col l3 m4">
          <h3>HTML and CSS</h3>
          <a class="w3-bar-item w3-button" href="/html/default.asp">Learn HTML</a>
          <a class="w3-bar-item w3-button" href="/css/default.asp">Learn CSS</a>
          <a class="w3-bar-item w3-button" href="/w3css/default.asp">Learn W3.CSS</a>
          <a class="w3-bar-item w3-button" href="/colors/default.asp">Learn Colors</a>
          <a class="w3-bar-item w3-button" href="/bootstrap/default.asp">Learn Bootstrap 3</a>
          <a class="w3-bar-item w3-button" href="/bootstrap4/default.asp">Learn Bootstrap 4</a>
          <a class="w3-bar-item w3-button" href="/graphics/default.asp">Learn Graphics</a>
          <a class="w3-bar-item w3-button" href="/icons/default.asp">Learn Icons</a>
          <a class="w3-bar-item w3-button" href="/howto/default.asp">Learn How To</a>
        </div>
        <div class="w3-col l3 m4">
          <h3>JavaScript</h3>
          <a class="w3-bar-item w3-button" href="/js/default.asp">Learn JavaScript</a>
          <a class="w3-bar-item w3-button" href="/jquery/default.asp">Learn jQuery</a>
          <a class="w3-bar-item w3-button" href="/angular/default.asp">Learn AngularJS</a>
          <a class="w3-bar-item w3-button" href="/js/js_json_intro.asp">Learn JSON</a>
          <a class="w3-bar-item w3-button" href="/js/js_ajax_intro.asp">Learn AJAX</a>
          <div class="w3-hide-small"><br><br></div>
        </div>
        <div class="w3-col l3 m4">
          <h3>Server Side</h3>
          <a class="w3-bar-item w3-button" href="/sql/default.asp">Learn SQL</a>
          <a class="w3-bar-item w3-button" href="/php/default.asp">Learn PHP</a>
          <a class="w3-bar-item w3-button" href="/asp/default.asp">Learn ASP</a>
          <a class="w3-bar-item w3-button" href="/nodejs/default.asp">Learn Node.js</a>
          <a class="w3-bar-item w3-button" href="/nodejs/nodejs_raspberrypi.asp">Learn Raspberry Pi</a>
          <h3>Web Building</h3>
          <a class="w3-bar-item w3-button" href="/w3css/w3css_templates.asp">Web Templates</a>
          <a class="w3-bar-item w3-button" href="/browsers/default.asp">Web Statistics</a>
          <a class="w3-bar-item w3-button" href="/cert/default.asp">Web Certificates</a>
        </div>
        <div class="w3-col l3 m4">
          <h3>XML</h3>
          <a class="w3-bar-item w3-button" href="/xml/default.asp">Learn XML</a>
          <a class="w3-bar-item w3-button" href="/xml/ajax_intro.asp">Learn XML AJAX</a>
          <a class="w3-bar-item w3-button" href="/xml/dom_intro.asp">Learn XML DOM</a>
          <a class="w3-bar-item w3-button" href="/xml/xml_dtd_intro.asp">Learn XML DTD</a>
          <a class="w3-bar-item w3-button" href="/xml/schema_intro.asp">Learn XML Schema</a>
          <a class="w3-bar-item w3-button" href="/xml/xsl_intro.asp">Learn XSLT</a>
          <a class="w3-bar-item w3-button" href="/xml/xpath_intro.asp">Learn XPath</a>
          <a class="w3-bar-item w3-button" href="/xml/xquery_intro.asp">Learn XQuery</a>
        </div>
      </div>
      <br>
    </div>
    <div id="nav_references" class="w3-bar-block w3-card-2">
      <span onclick="w3_close_nav(&quot;references&quot;)" class="w3-button w3-xlarge w3-right" style="position:absolute;right:0;font-weight:bold;">×</span>
      <div class="w3-row-padding" style="padding:24px 48px">
        <div class="w3-col m4">
          <h3>HTML</h3>
          <a class="w3-bar-item w3-button" href="/tags/default.asp">HTML Tag Reference</a>
          <a class="w3-bar-item w3-button" href="/tags/ref_eventattributes.asp">HTML Event Reference</a>
          <a class="w3-bar-item w3-button" href="/colors/default.asp">HTML Color Reference</a>
          <a class="w3-bar-item w3-button" href="/tags/ref_attributes.asp">HTML Attribute Reference</a>
          <a class="w3-bar-item w3-button" href="/tags/ref_canvas.asp">HTML Canvas Reference</a>
          <a class="w3-bar-item w3-button" href="/graphics/svg_reference.asp">HTML SVG Reference</a>
          <a class="w3-bar-item w3-button" href="/graphics/google_maps_reference.asp">Google Maps Reference</a>
          <h3>CSS</h3>
          <a class="w3-bar-item w3-button" href="/cssref/default.asp">CSS Reference</a>
          <a class="w3-bar-item w3-button" href="/cssref/css3_browsersupport.asp">CSS Browser Support</a>
          <a class="w3-bar-item w3-button" href="/cssref/css_selectors.asp">CSS Selector Reference</a>
          <a class="w3-bar-item w3-button" href="/w3css/w3css_references.asp">W3.CSS Reference</a>
          <a class="w3-bar-item w3-button" href="/bootstrap/bootstrap_ref_all_classes.asp">Bootstrap Reference</a>
          <a class="w3-bar-item w3-button" href="/icons/icons_reference.asp">Icon Reference</a>
        </div>
        <div class="w3-col m4">
          <h3>JavaScript</h3>
          <a class="w3-bar-item w3-button" href="/jsref/default.asp">JavaScript Reference</a>
          <a class="w3-bar-item w3-button" href="/jsref/default.asp">HTML DOM Reference</a>
          <a class="w3-bar-item w3-button" href="/jquery/jquery_ref_selectors.asp">jQuery Reference</a>
          <a class="w3-bar-item w3-button" href="/angular/angular_ref_directives.asp">AngularJS Reference</a>
          <a class="w3-bar-item w3-button" href="/w3js/w3js_references.asp">W3.JS Reference</a>
          <h3>XML</h3>
          <a class="w3-bar-item w3-button" href="/xml/dom_nodetype.asp">XML Reference</a>
          <a class="w3-bar-item w3-button" href="/xml/dom_http.asp">XML Http Reference</a>
          <a class="w3-bar-item w3-button" href="/xml/xsl_elementref.asp">XSLT Reference</a>
          <a class="w3-bar-item w3-button" href="/xml/schema_elements_ref.asp">XML Schema Reference</a>
        </div>
        <div class="w3-col m4">
          <h3>Charsets</h3>
          <a class="w3-bar-item w3-button" href="/charsets/default.asp">HTML Character Sets</a>
          <a class="w3-bar-item w3-button" href="/charsets/ref_html_ascii.asp">HTML ASCII</a>
          <a class="w3-bar-item w3-button" href="/charsets/ref_html_ansi.asp">HTML ANSI</a>
          <a class="w3-bar-item w3-button" href="/charsets/ref_html_ansi.asp">HTML Windows-1252</a>
          <a class="w3-bar-item w3-button" href="/charsets/ref_html_8859.asp">HTML ISO-8859-1</a>
          <a class="w3-bar-item w3-button" href="/charsets/ref_html_symbols.asp">HTML Symbols</a>
          <a class="w3-bar-item w3-button" href="/charsets/ref_html_utf8.asp">HTML UTF-8</a>
          <h3>Server Side</h3>
          <a class="w3-bar-item w3-button" href="/php/php_ref_array.asp">PHP Reference</a>
          <a class="w3-bar-item w3-button" href="/sql/sql_quickref.asp">SQL Reference</a>
          <a class="w3-bar-item w3-button" href="/asp/asp_ref_response.asp">ASP Reference</a>
        </div>
      </div>
      <br>
    </div>
    <div id="nav_examples" class="w3-bar-block w3-card-2">
      <span onclick="w3_close_nav(&quot;examples&quot;)" class="w3-button w3-xlarge w3-right" style="position:absolute;right:0;font-weight:bold;">×</span>
      <div class="w3-row-padding" style="padding:24px 48px">
        <div class="w3-col l3 m6">
          <h3>HTML/CSS</h3>
          <a class="w3-bar-item w3-button" href="/html/html_examples.asp">HTML Examples</a>
          <a class="w3-bar-item w3-button" href="/css/css_examples.asp">CSS Examples</a>
          <a class="w3-bar-item w3-button" href="/w3css/w3css_examples.asp">W3.CSS Examples</a>
          <a class="w3-bar-item w3-button" href="/w3css/w3css_templates.asp">W3.CSS Templates</a>
          <a class="w3-bar-item w3-button" href="/bootstrap/bootstrap_examples.asp">Bootstrap Examples</a>
        </div>
        <div class="w3-col l3 m6">
          <h3>JavaScript</h3>
          <a class="w3-bar-item w3-button" href="/js/js_examples.asp" target="_top">JavaScript Examples</a>
          <a class="w3-bar-item w3-button" href="/js/js_dom_examples.asp" target="_top">HTML DOM Examples</a>
          <a class="w3-bar-item w3-button" href="/jquery/jquery_examples.asp" target="_top">jQuery Examples</a>
          <a class="w3-bar-item w3-button" href="/angular/angular_examples.asp" target="_top">AngularJS Examples</a>
          <a class="w3-bar-item w3-button" href="/js/js_ajax_examples.asp" target="_top">AJAX Examples</a>
          <a class="w3-bar-item w3-button" href="/w3js/w3js_examples.asp">W3.JS Examples</a>
        </div>
        <div class="w3-col l3 m6">
          <h3>Server Side</h3>
          <a class="w3-bar-item w3-button" href="/php/php_examples.asp" target="_top">PHP Examples</a>
          <a class="w3-bar-item w3-button" href="/asp/asp_examples.asp" target="_top">ASP Examples</a>
          <h3>XML</h3>
          <a class="w3-bar-item w3-button" href="/xml/xml_examples.asp" target="_top">XML Examples</a>
          <a class="w3-bar-item w3-button" href="/xml/xsl_examples.asp" target="_top">XSLT Examples</a>
          <a class="w3-bar-item w3-button" href="/xml/xpath_examples.asp" target="_top">XPath Examples</a>
          <a class="w3-bar-item w3-button" href="/xml/schema_example.asp" target="_top">XML Schema Examples</a>
          <a class="w3-bar-item w3-button" href="/graphics/svg_examples.asp" target="_top">SVG Examples</a>
        </div>
        <div class="w3-col l3 m6">
          <h3>Quizzes</h3>
          <a class="w3-bar-item w3-button" href="/quiztest/quiztest.asp?Qtest=HTML" target="_top">HTML Quiz</a>
          <a class="w3-bar-item w3-button" href="/quiztest/quiztest.asp?Qtest=CSS" target="_top">CSS Quiz</a>
          <a class="w3-bar-item w3-button" href="/quiztest/quiztest.asp?Qtest=JavaScript" target="_top">JavaScript Quiz</a>
          <a class="w3-bar-item w3-button" href="/quiztest/quiztest.asp?Qtest=Bootstrap" target="_top">Bootstrap Quiz</a>
          <a class="w3-bar-item w3-button" href="/quiztest/quiztest.asp?Qtest=jQuery" target="_top">jQuery Quiz</a>
          <a class="w3-bar-item w3-button" href="/quiztest/quiztest.asp?Qtest=PHP" target="_top">PHP Quiz</a>
          <a class="w3-bar-item w3-button" href="/quiztest/quiztest.asp?Qtest=SQL" target="_top">SQL Quiz</a>
          <a class="w3-bar-item w3-button" href="/quiztest/quiztest.asp?Qtest=XML" target="_top">XML Quiz</a>
        </div>
      </div>
      <br>
    </div>
  </div>
</div>

HT_13/ht_13/news/templates/news/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>


<h3><a href="/results/get_data">Update Data</a></h3>

</body>
</html>

HT_13/ht_13/news/templates/news/menu.html
<div class="w3-sidebar w3-collapse" id="sidenav" style="top: 112px; display: none;">
  <div id="leftmenuinner" style="padding-top: 112px;">
    <div class="w3-light-grey" id="leftmenuinnerinner">
      <a href="javascript:void(0)" onclick="close_menu()" class="w3-button w3-hide-large w3-large w3-display-topright" style="right:16px;padding:3px 12px;font-weight:bold;">×</a>
<h2 class="left"><span class="left_h2">W3Schools</span> Quizzes</h2>
<a target="_top" href="quiztest.asp?Qtest=HTML">Quiz HTML</a>
<a target="_top" href="quiztest.asp?qtest=CSS">Quiz CSS</a>
<a target="_top" href="quiztest.asp?qtest=JavaScript">Quiz JavaScript</a>
<a target="_top" href="quiztest.asp?qtest=Bootstrap">Quiz Bootstrap</a>
<a target="_top" href="quiztest.asp?qtest=jQuery">Quiz jQuery</a>
<a target="_top" href="quiztest.asp?qtest=PHP">Quiz PHP</a>
<a target="_top" href="quiztest.asp?qtest=SQL" class="active">Quiz SQL</a>
<a target="_top" href="quiztest.asp?qtest=XML">Quiz XML</a>

      <br><br>
    </div>
  </div>
</div>

HT_13/ht_13/news/templates/news/results.html
{% extends 'news/base.html' %}

{% block title %}Stories{% endblock %}

{% block content %}

<div class="w3-main w3-light-grey" id="belowtopnav" style="margin-left: 220px; padding-top: 0px;">
  <div class="w3-row w3-white">
    <div class="w3-col l10 m12" id="main">
      <div id="mainLeaderboard" style="overflow:hidden;">
        <div id="div-gpt-ad-1422003450156-2" data-google-query-id="CJjI29nTjNkCFQ-CGQodwrgJOQ">
          <script type="text/javascript">googletag.cmd.push(function() { googletag.display('div-gpt-ad-1422003450156-2'); });</script>
        <div id="google_ads_iframe_/16833175/MainLeaderboard_0__container__" style="border: 0pt none; display: inline-block; width: 728px; height: 90px;"><iframe frameborder="0" src="https://tpc.googlesyndication.com/safeframe/1-0-15/html/container.html" id="google_ads_iframe_/16833175/MainLeaderboard_0" title="3rd party ad content" name="" scrolling="no" marginwidth="0" marginheight="0" width="728" height="90" data-is-safeframe="true" style="border: 0px; vertical-align: bottom;"></iframe></div></div>
      </div>
<h1 style="text-align: center">Our Stories</h1>

<div class="container">

  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Ask Stories</th>
      </tr>
    </thead>
    <tbody>
    {% for story in askstories_list %}
         <tr>
        <td><a href="{% url 'news:story_detail' story.id%}">{{ story.title }}</a></td>
      </tr>
    {% endfor %}
    </tbody>

    <thead>
      <tr>
        <th>Show Stories</th>
      </tr>
    </thead>
    <tbody>
    {% for story in showstories_list %}
         <tr>
        <td><a href="{% url 'news:story_detail' story.id%}">{{ story.title }}</a></td>
      </tr>
    {% endfor %}
    </tbody>

   <thead>
      <tr>
        <th>Job Stories</th>
      </tr>
    </thead>
    <tbody>
    {% for story in jobstories_list %}
         <tr>
        <td><a href="{% url 'news:story_detail' story.id%}">{{ story.title }}</a></td>
      </tr>
    {% endfor %}
    </tbody>


     <thead>
      <tr>
        <th>New Stories</th>
      </tr>
    </thead>
    <tbody>
    {% for story in newstories_list %}
         <tr>
        <td><a href="{% url 'news:story_detail' story.id%}">{{ story.title }}</a></td>
      </tr>
    {% endfor %}
    </tbody>

  </table>
</div>

{% endblock %}