HT_12/ht_12/ht_12/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

HT_12/ht_12/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailsView.as_view(), name='details'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

HT_12/ht_12/polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

HT_12/ht_12/polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic

from .models import Question, Choice


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]


class DetailsView(generic.DetailView):
    model = Question
    template_name = 'polls/details.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     context = {'latest_question_list': latest_question_list}
#
#     return render(request, 'polls/index.html', context)
#
#
# def details(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#
#     return render(request, 'polls/details.html', {'question': question})
#
#
# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/results.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/details.html', {
            'question': question,
            'error_message': "You didn't select a choice",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
    return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))

HT_12/ht_12/polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% block scripts %}
    <link href="https://s3.us-east-2.amazonaws.com/python-test123/bootstrap.min.css" rel="stylesheet" media="screen">
    <script src="https://s3.us-east-2.amazonaws.com/python-test123/bootstrap.min.js"></script>
    {% endblock %}
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

HT_12/ht_12/polls/templates/polls/details.html
{% extends "polls/base.html" %}


{% block content %}

<h1 style="padding: 20px">{{ question.question_text }}</h1>

{% if error_message %} <p><strong> {{ error_message }}</strong></p> {% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}

    <div style="padding-left: 20px; padding-right: 1000px" class="input-group">
        <div class="input-group-prepend">
            <div class="input-group-text">
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
            </div>
        </div>
        <label class="form-control" for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    </div>

{% endfor %}

<div style="padding: 20px">
    <input type="submit" class="btn btn-info" value="Vote" />
</div>
</form>

{% endblock %}

HT_12/ht_12/polls/templates/polls/index.html
{% extends "polls/base.html" %}

{% block content %}
   <h1 style="padding: 20px">Questions</h1>
   {% if latest_question_list %}
    <ul class="list-group" style="padding: 20px; padding-right: 1000px">
    {% for question in latest_question_list %}
        <li class="list-group-item"><a href="{% url 'polls:details' question.id %}">{{ question.question_text }}</a> </li>
    {% endfor %}
    </ul>

    {% else %}
        <p>No polls are available</p>
    {% endif %}

{% endblock %}

HT_12/ht_12/polls/templates/polls/results.html
{% extends "polls/base.html" %}

{% block content %}

<h1 style="padding: 20px">{{ question.question_text }} - Results</h1>

<ul class="list-group" style="padding: 20px; padding-right: 1000px">
    {% for choice in question.choice_set.all %}
        <li class="list-group-item">{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<div style="padding: 20px">
    <a class="btn btn-info" href="{% url 'polls:details' question.id %}">Vote again?</a>
</div>

{% endblock %}